version: '3.4'
services:
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./data/database.sql:/docker-entrypoint-initdb.d/database.sql
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
      target: development_build
    container_name: wordpress
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DB_HOST: db:3306A
      DB_USER: wordpress
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      POSTCLICK_ENVIRONMENT: dev
      WP_DEBUG: enable
      GCS_BUCKET_NAME: 'postclick_media'
      WP_SITEURL: 'http://postclick.local'
    volumes:
      - ./app/:/var/www/app
      - ./vendor:/var/www/vendor
      - ./docker/wordpress/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
volumes:
  db_data: {}